export const countries = [
  { country: "Afganistan", code: "AF" },
  { country: "Albania", code: "AL" },
  { country: "Algieria", code: "DZ" },
  { country: "Andora", code: "AD" },
  { country: "Angola", code: "AO" },
  { country: "Antigua i Barbuda", code: "AG" },
  { country: "Arabia Saudyjska", code: "SA" },
  { country: "Argentyna", code: "AR" },
  { country: "Armenia", code: "AM" },
  { country: "Australia", code: "AU" },
  { country: "Austria", code: "AT" },
  { country: "Azerbejdżan", code: "AZ" },
  { country: "Bahamy", code: "BS" },
  { country: "Bahrajn", code: "BH" },
  { country: "Bangladesz", code: "BD" },
  { country: "Barbados", code: "BB" },
  { country: "Belgia", code: "BE" },
  { country: "Belize", code: "BZ" },
  { country: "Benin", code: "BJ" },
  { country: "Bhutan", code: "BT" },
  { country: "Białoruś", code: "BY" },
  { country: "Birma (Myanmar)", code: "MM" },
  { country: "Boliwia", code: "BO" },
  { country: "Bośnia i Hercegowina", code: "BA" },
  { country: "Botswana", code: "BW" },
  { country: "Brazylia", code: "BR" },
  { country: "Brunei", code: "BN" },
  { country: "Bułgaria", code: "BG" },
  { country: "Burkina Faso", code: "BF" },
  { country: "Burundi", code: "BI" },
  { country: "Chile", code: "CL" },
  { country: "Chiny", code: "CN" },
  { country: "Chorwacja", code: "HR" },
  { country: "Cypr", code: "CY" },
  { country: "Czad", code: "TD" },
  { country: "Czarnogóra", code: "ME" },
  { country: "Czechy", code: "CZ" },
  { country: "Dania", code: "DK" },
  { country: "Demokratyczna Republika Konga", code: "CD" },
  { country: "Dominika", code: "DM" },
  { country: "Dominikana", code: "DO" },
  { country: "Dżibuti", code: "DJ" },
  { country: "Egipt", code: "EG" },
  { country: "Ekwador", code: "EC" },
  { country: "Erytrea", code: "ER" },
  { country: "Estonia", code: "EE" },
  { country: "Eswatini", code: "SZ" },
  { country: "Etiopia", code: "ET" },
  { country: "Fidżi", code: "FJ" },
  { country: "Filipiny", code: "PH" },
  { country: "Finlandia", code: "FI" },
  { country: "Francja", code: "FR" },
  { country: "Gabon", code: "GA" },
  { country: "Gambia", code: "GM" },
  { country: "Ghana", code: "GH" },
  { country: "Grecja", code: "GR" },
  { country: "Grenada", code: "GD" },
  { country: "Gruzja", code: "GE" },
  { country: "Gujana", code: "GY" },
  { country: "Gwatemala", code: "GT" },
  { country: "Gwinea", code: "GN" },
  { country: "Gwinea Bissau", code: "GW" },
  { country: "Gwinea Równikowa", code: "GQ" },
  { country: "Haiti", code: "HT" },
  { country: "Hiszpania", code: "ES" },
  { country: "Holandia", code: "NL" },
  { country: "Honduras", code: "HN" },
  { country: "Indie", code: "IN" },
  { country: "Indonezja", code: "ID" },
  { country: "Irak", code: "IQ" },
  { country: "Iran", code: "IR" },
  { country: "Irlandia", code: "IE" },
  { country: "Islandia", code: "IS" },
  { country: "Izrael", code: "IL" },
  { country: "Jamajka", code: "JM" },
  { country: "Japonia", code: "JP" },
  { country: "Jemen", code: "YE" },
  { country: "Jordania", code: "JO" },
  { country: "Kambodża", code: "KH" },
  { country: "Kamerun", code: "CM" },
  { country: "Kanada", code: "CA" },
  { country: "Katar", code: "QA" },
  { country: "Kazachstan", code: "KZ" },
  { country: "Kenia", code: "KE" },
  { country: "Kirgistan", code: "KG" },
  { country: "Kiribati", code: "KI" },
  { country: "Kolumbia", code: "CO" },
  { country: "Komory", code: "KM" },
  { country: "Kongo", code: "CG" },
  { country: "Korea Południowa", code: "KR" },
  { country: "Korea Północna", code: "KP" },
  { country: "Kostaryka", code: "CR" },
  { country: "Kuba", code: "CU" },
  { country: "Kuwejt", code: "KW" },
  { country: "Laos", code: "LA" },
  { country: "Lesotho", code: "LS" },
  { country: "Liban", code: "LB" },
  { country: "Liberia", code: "LR" },
  { country: "Libia", code: "LY" },
  { country: "Liechtenstein", code: "LI" },
  { country: "Litwa", code: "LT" },
  { country: "Luksemburg", code: "LU" },
  { country: "Łotwa", code: "LV" },
  { country: "Macedonia Północna", code: "MK" },
  { country: "Madagaskar", code: "MG" },
  { country: "Malawi", code: "MW" },
  { country: "Malediwy", code: "MV" },
  { country: "Malezja", code: "MY" },
  { country: "Mali", code: "ML" },
  { country: "Malta", code: "MT" },
  { country: "Maroko", code: "MA" },
  { country: "Mauretania", code: "MR" },
  { country: "Mauritius", code: "MU" },
  { country: "Meksyk", code: "MX" },
  { country: "Mikronezja", code: "FM" },
  { country: "Mołdawia", code: "MD" },
  { country: "Monako", code: "MC" },
  { country: "Mongolia", code: "MN" },
  { country: "Mozambik", code: "MZ" },
  { country: "Namibia", code: "NA" },
  { country: "Nauru", code: "NR" },
  { country: "Nepal", code: "NP" },
  { country: "Niemcy", code: "DE" },
  { country: "Niger", code: "NE" },
  { country: "Nigeria", code: "NG" },
  { country: "Nikaragua", code: "NI" },
  { country: "Norwegia", code: "NO" },
  { country: "Nowa Zelandia", code: "NZ" },
  { country: "Oman", code: "OM" },
  { country: "Pakistan", code: "PK" },
  { country: "Palau", code: "PW" },
  { country: "Panama", code: "PA" },
  { country: "Papua-Nowa Gwinea", code: "PG" },
  { country: "Paragwaj", code: "PY" },
  { country: "Peru", code: "PE" },
  { country: "Polska", code: "PL" },
  { country: "Portugalia", code: "PT" },
  { country: "Republika Południowej Afryki", code: "ZA" },
  { country: "Republika Środkowoafrykańska", code: "CF" },
  { country: "Republika Zielonego Przylądka", code: "CV" },
  { country: "Rosja", code: "RU" },
  { country: "Rumunia", code: "RO" },
  { country: "Rwanda", code: "RW" },
  { country: "Saint Kitts i Nevis", code: "KN" },
  { country: "Saint Lucia", code: "LC" },
  { country: "Saint Vincent i Grenadyny", code: "VC" },
  { country: "Salwador", code: "SV" },
  { country: "Samoa", code: "WS" },
  { country: "San Marino", code: "SM" },
  { country: "Senegal", code: "SN" },
  { country: "Serbia", code: "RS" },
  { country: "Seszele", code: "SC" },
  { country: "Sierra Leone", code: "SL" },
  { country: "Singapur", code: "SG" },
  { country: "Słowacja", code: "SK" },
  { country: "Słowenia", code: "SI" },
  { country: "Somalia", code: "SO" },
  { country: "Sri Lanka", code: "LK" },
  { country: "Stany Zjednoczone", code: "US" },
  { country: "Suazi", code: "SZ" },
  { country: "Sudan", code: "SD" },
  { country: "Sudan Południowy", code: "SS" },
  { country: "Surinam", code: "SR" },
  { country: "Syria", code: "SY" },
  { country: "Szwajcaria", code: "CH" },
  { country: "Szwecja", code: "SE" },
  { country: "Tadżykistan", code: "TJ" },
  { country: "Tajlandia", code: "TH" },
  { country: "Tanzania", code: "TZ" },
  { country: "Timor Wschodni", code: "TL" },
  { country: "Togo", code: "TG" },
  { country: "Tonga", code: "TO" },
  { country: "Trynidad i Tobago", code: "TT" },
  { country: "Tunezja", code: "TN" },
  { country: "Turcja", code: "TR" },
  { country: "Turkmenistan", code: "TM" },
  { country: "Tuvalu", code: "TV" },
  { country: "Uganda", code: "UG" },
  { country: "Ukraina", code: "UA" },
  { country: "Urugwaj", code: "UY" },
  { country: "Uzbekistan", code: "UZ" },
  { country: "Vanuatu", code: "VU" },
  { country: "Watykan", code: "VA" },
  { country: "Wenezuela", code: "VE" },
  { country: "Węgry", code: "HU" },
  { country: "Wielka Brytania", code: "GB" },
  { country: "Wietnam", code: "VN" },
  { country: "Włochy", code: "IT" },
  { country: "Wybrzeże Kości Słoniowej", code: "CI" },
  { country: "Wyspy Marshalla", code: "MH" },
  { country: "Wyspy Salomona", code: "SB" },
  { country: "Wyspy Świętego Tomasza i Książęca", code: "ST" },
  { country: "Zambia", code: "ZM" },
  { country: "Zimbabwe", code: "ZW" },
];
